export default (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    version="1.2"
    viewBox="0 0 24 24"
  >
    <defs>
      <image
        id="img1"
        width="24"
        height="22"
        href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAWCAMAAADto6y6AAAAAXNSR0IB2cksfwAAANVQTFRFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADmVSEQAAAEd0Uk5TAAdVxMxmCiKI6//wkQJKtf3KYA9v3fiqRDOZ9XcU1jw1n/cTdeo6BYb65ONHSOmKnAQkJamys6ce8ZWWHUvNSQ1G6BF7ehByMhCOAAAA2ElEQVR4nF2Q1xaCMBBEY8dREHtBxQJq7L0L9v//JKMGCNwXhrmbzTkhxCEUjkRjcRIkISXBSKUTYisrGRXI5nJZQM0oMq/zhSJQKle+uVrTgGK94Y//sVjzO6aTVrvDhLiYnWcVC13j93EBjC5vgsJtABMupk/4EUTP26R7oh+8o8/TAFQUFAOehtBFoWPEUxJjUUww5WkGzL1+Dkg8LmYqXTr9iqrSwp1aY8PfWt5iJ6zdH3D8GfmE1Fm88EJh2derYoHaxMft/n+Ne4UEeDwtTYu+3s7/B8VQE8TuitivAAAAAElFTkSuQmCC"
      ></image>
    </defs>
    <style></style>
    <use href="#img1"></use>
  </svg>
);
